version: "3.9"

services:

  postgres:
    container_name: "postgres"
    image: postgres
    volumes:
      - postgres-data:/postgres/postgres-data
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  postgres-data: